version: '3.3'
services:
  redissubmit1:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/submit1:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"
#  redissubmit2:
#    image: redis
#    logging:
#      driver: "none"
#    volumes:
#      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
#      - "./data/redis/submit2:/var/run/redis"
#    command: "redis-server /usr/local/etc/redis/redis.conf"
  redisvalidator1:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator1:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"
  redisvalidator2:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator2:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  redisvalidator3:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator3:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"

#  redisdemo1:
#    image: redis
#    logging:
#      driver: "none"
#    volumes:
#      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
#      - "./data/redis/demo1:/var/run/redis"
#    command: "redis-server /usr/local/etc/redis/redis.conf"
#  redisdemo2:
#    image: redis
#    logging:
#      driver: "none"
#    volumes:
#      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
#      - "./data/redis/demo2:/var/run/redis"
#    command: "redis-server /usr/local/etc/redis/redis.conf"

  submit1:
    build: ./plasma-core
    ports:
      - "8081:80"
      - "40301:30301"
      - "40301:30301/udp"
    volumes:
      - "./data/logs/plasma-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
      - "./data/redis/submit1:/var/run/redis"
    links:
      - redissubmit1
      - validator1
      - validator2
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'

#  submit2:
#    build: ./plasma-core
#    ports:
#      - "8082:80"
#      - "40302:30301"
#      - "40302:30301/udp"
#    volumes:
#      - "./data/logs/plasma-core:/usr/src/app/app/logs"
#      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
#      - "./data/redis/submit2:/var/run/redis"
#    links:
#      - redissubmit2
#      - validator1
#      - validator2
#    environment:
#      NODE_ENV: development
#      LOG_LEVEL: "info"
#      PRODUCTION_MODE: "OFF"
#    #    command: 'npm run development'
#    logging:
#      options:
#        max-size: 1000m
#    restart: 'no'

  validator1:
    build: ./plasma-core
    ports:
      - "8083:80"
      - "40303:30301"
      - "40303:30301/udp"
    volumes:
      - "./data/logs/plasma-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
      - "./data/redis/validator1:/var/run/redis"
    links:
      - redisvalidator1
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  validator2:
    build: ./plasma-core
    ports:
      - "8084:80"
      - "40304:30301"
      - "40304:30301/udp"
    volumes:
      - "./data/logs/plasma-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
      - "./data/redis/validator2:/var/run/redis"
    links:
      - redisvalidator2
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'

  validator3:
    build: ./plasma-core
    ports:
      - "8085:80"
      - "40305:30301"
      - "40305:30301/udp"
    volumes:
      - "./data/logs/plasma-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
      - "./data/redis/validator3:/var/run/redis"
    links:
      - redisvalidator3
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'

#
#  demo1:
#    build: ./plasma-core
#    ports:
#      - "8085:80"
#      - "40305:30301"
#      - "40305:30301/udp"
#    volumes:
#      - "./data/logs/plasma-core:/usr/src/app/app/logs"
#      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
#      - "./data/redis/demo1:/var/run/redis"
#    links:
#      - redisdemo1
#    environment:
#      NODE_ENV: development
#      LOG_LEVEL: "info"
#      PRODUCTION_MODE: "OFF"
#    #    command: 'npm run development'
#    logging:
#      options:
#        max-size: 1000m
#    restart: 'no'
#
#  demo2:
#    build: ./plasma-core
#    ports:
#      - "8086:80"
#      - "40306:30301"
#      - "40306:30301/udp"
#    volumes:
#      - "./data/logs/plasma-core:/usr/src/app/app/logs"
#      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
#      - "./data/redis/demo2:/var/run/redis"
#    links:
#      - redisdemo2
#    environment:
#      NODE_ENV: development
#      LOG_LEVEL: "info"
#      PRODUCTION_MODE: "OFF"
#    #    command: 'npm run development'
#    logging:
#      options:
#        max-size: 1000m
#    restart: 'no'