version: '3.3'
services:
  mongoboot:
    image: mongo
  mongovalidator1:
    image: mongo
  mongovalidator2:
    image: mongo

  redisboot:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/boot:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  redisvalidator1:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator1:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"
  redisvalidator2:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator2:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  redisvalidator3:
    image: redis
    logging:
      driver: "none"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./data/redis/validator3:/var/run/redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  boot:
    build: ./plasma-core
    ports:
      - "8080:80"
      - "9000:9000"
    volumes:
      - "./data/redis/boot:/var/run/redis"
    links:
      - redisboot
      - mongoboot
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'


  validator1:
    build: ./plasma-core
    ports:
      - "8081:80"
    volumes:
      - "./data/redis/validator1:/var/run/redis"
    links:
      - redisvalidator1
      - mongovalidator1
      - boot
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"
      NODES: ws://boot:9000
    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'


  demo:
    build: ./plasma-core
    volumes:
      - "./data/redis/boot:/var/run/redis"

    links:
      - redisboot
      - mongoboot
      - boot
    environment:
      NODE_ENV: development
      LOG_LEVEL: "info"
      PRODUCTION_MODE: "OFF"

    #    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'
