version: '3.3'
services:
  ethernode:
    build: ./ethernode
    environment:
      LOG_LEVEL: 0 #0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=detail
      DELETE_OLD_BLOCKCHAIN: 1
      MINING: 1
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    volumes:
      - ./ethernode/devnet:/root/devnet
      - ./ethernode/rinkeby:/root/rinkeby
      - ./data/ethernode/.ethereum:/root/.ethereum
      - ./data/ethernode/.ethash:/root/.ethash
      - ./data/ethernode/geth_ipc:/root/geth_ipc
    logging:
      options:
        max-size: 1000m
    restart: "no"
    entrypoint: "/root/devnet.sh"

  truffle:
    build: ./truffle
    #stdin_open: true
    tty: true
    environment:
      HOST: ethernode
    links:
      - ethernode
    volumes:
      - ./truffle/app:/usr/src/app
    logging:
      options:
        max-size: 1000m
    restart: "no"
